# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a6NxIWKDa_dhI3ZbMRHR0DX5lh8WpwWF
"""

# Collection or binary conversions and algorithms
from . import ascii
from . import base2
from . import base10
from . import base16

__all__ = [
    'ascii',
    'base2',
    'base10',
    'base16'
]